dataset:
  data_dir: ${hydra:runtime.cwd}/../data/labeled_img
  train_start: 2015-01-01
  test_start: 2019-01-01 
  test_stop: 2019-12-31
  max_regions: 100
model: 
  _target_: models.LogisticClassifier
  num_features: 5152
batch_size: 128
fire_weight: 5
n_epoch: 3
lr: 0.001
hydra:
  run:
    dir: outputs/${now:%Y-%m-%d_%H-%M-%S}_logistic_maxregions=${dataset.max_regions}_firwgt=${fire_weight}